import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import SideNav from "@/component/SideNav";
import NextTopLoader from "nextjs-toploader";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Sahyog Home Mart | Showa inventory Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/store-logo.png" />
      </head>
      <body
        className={`${nunitoSans.variable} antialiased`}
        style={{ fontFamily: "var(--font-nunito-sans)" }}
      >
        <NextTopLoader color="#FFA503" showSpinner={false} />
        <SideNav>{children}</SideNav>
      </body>
    </html>
  );
}
