import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/component/SideNav";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sahyog Home Mart | Showa inventory Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/store-logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader color="#FFA503" showSpinner={false} />
        <SideNav>{children}</SideNav>
      </body>
    </html>
  );
}
